# Generated by Django 3.2.12 on 2023-03-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlog',
            name='food_entry_date',
            field=models.DateField(),
        ),
    ]
