# Generated by Django 3.2.12 on 2023-03-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_foodlog_food_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlog',
            name='food_entry_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
